const BASE_API_URL = "http://localhost:4000";

const MOVIES_IN_THEATERS = "movies-in-theaters";
const MOVIES_COMING = "movies-coming";
const TOP_RATED_MOVIES_INDIA = "top-rated-india";
const TOP_RATED_MOVIES = "top-rated-movies";
const FAVOURITE_MOVIES = "favourite";

const MOVIES_IN_THEATERS_URL = BASE_API_URL + "/" + MOVIES_IN_THEATERS;
const MOVIES_COMING_URL = BASE_API_URL + "/" + MOVIES_COMING;
const TOP_RATED_MOVIES_INDIA_URL = BASE_API_URL + "/" + TOP_RATED_MOVIES_INDIA;
const TOP_RATED_MOVIES_URL = BASE_API_URL + "/" + TOP_RATED_MOVIES;
const FAVOURITE_MOVIES_URL = BASE_API_URL + "/" + FAVOURITE_MOVIES;

export { 
    BASE_API_URL,

    MOVIES_IN_THEATERS, 
    MOVIES_COMING,
    TOP_RATED_MOVIES_INDIA,
    TOP_RATED_MOVIES,
    FAVOURITE_MOVIES,

    MOVIES_IN_THEATERS_URL,
    MOVIES_COMING_URL,
    TOP_RATED_MOVIES_INDIA_URL,
    TOP_RATED_MOVIES_URL,
    FAVOURITE_MOVIES_URL, 
};